### ISSUE TITLE
Cannot generate grammar caused by panic

### ISSUE THREAD

**Issue by CityOfLight77** [nautilus-fuzz/nautilus#15]
Panic when generating grammar. Here is my setup on ubuntu 20.04
```sh
cityoflight@nautilus:~/nautilus$ rustc -V
rustc 1.57.0-nightly (9dd4ce80f 2021-09-17)
```

```sh
cityoflight@nautilus:~/nautilus$ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

Panic trace
```sh
cityoflight@nautilus:~/nautilus$ RUST_BACKTRACE=1 cargo run --bin generator -- -g grammars/grammar_py_example.py -t 2
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/generator -g grammars/grammar_py_example.py -t 2`
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`: The Python interpreter is not initalized and the `auto-initialize` feature is not enabled.

Consider calling `pyo3::prepare_freethreaded_python()` before attempting to use Python APIs.', /home/cityoflight/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.14.5/src/gil.rs:224:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9dd4ce80fb01d1ff5cb5002f08b7b3847b59e664/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/9dd4ce80fb01d1ff5cb5002f08b7b3847b59e664/library/core/src/panicking.rs:103:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/9dd4ce80fb01d1ff5cb5002f08b7b3847b59e664/library/core/src/panicking.rs:141:5
   4: pyo3::gil::GILGuard::acquire::{{closure}}
             at /home/cityoflight/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.14.5/src/gil.rs:224:21
   5: parking_lot::once::Once::call_once_force::{{closure}}
             at /home/cityoflight/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.2/src/once.rs:189:13
   6: parking_lot::once::Once::call_once_slow
             at /home/cityoflight/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.2/src/once.rs:304:9
   7: parking_lot::once::Once::call_once_force
             at /home/cityoflight/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.2/src/once.rs:188:9
   8: pyo3::gil::GILGuard::acquire
             at /home/cityoflight/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.14.5/src/gil.rs:220:17
   9: pyo3::python::Python::acquire_gil
             at /home/cityoflight/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.14.5/src/python.rs:214:9
  10: generator::python_grammar_loader::load_python_grammar
             at ./fuzzer/src/python_grammar_loader.rs:77:15
  11: generator::main
             at ./fuzzer/src/generator.rs:86:15
  12: core::ops::function::FnOnce::call_once
             at /rustc/9dd4ce80fb01d1ff5cb5002f08b7b3847b59e664/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by CityOfLight77** [comment]
After update pyo3 to 0.15.0 and adding `pyo3::prepare_freethreaded_python();` in  nautilus run successfully. Will make a PR soon
