### ISSUE TITLE
Cannot Compile Generator

### ISSUE THREAD

**Issue by JesseAusten** [nautilus-fuzz/nautilus#35]
The generator binary will not compile for me.

Not sure what details are relevant here.
Cargo version 1.61.0
Cloned `master`
Ubuntu 20.04

```
> RUST_BACKTRACE=1 cargo run --bin generator -- -g grammars/grammar_py_example.py -t 100
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `target/debug/generator -g grammars/grammar_py_example.py -t 100`
thread 'main' panicked at 'Mismatch between definition and access of `tree_depth`. Could not downcast to usize, need to downcast to alloc::string::String
', fuzzer/src/generator.rs:67:10
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:143:14
   2: clap::parser::error::MatchesError::unwrap
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.32/src/parser/error.rs:30:9
   3: clap::parser::matches::arg_matches::ArgMatches::get_one
             at /home/username/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-4.0.32/src/parser/matches/arg_matches.rs:113:9
   4: generator::main
             at ./fuzzer/src/generator.rs:66:23
   5: core::ops::function::FnOnce::call_once
             at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by rchildre3** [comment]
Fixed in #36
